name: Build and Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npx yarn

      - name: Build
        run: npx yarn build

      - name: Test
        run: npx yarn test

env:
  HUSKY: 0
